defaults:
  - _synthetic_env_base
  - _self_
name: ReachingHard
tags: "reaching-hard"
datadir: "datasets/ReachingHard-Seed0-Tr100000-Val10000.hdf5"
dataset_checkpoint:
    entity: ''
    project: ''
    run_id: ''
    file: 'ReachingHard-Seed0-Tr100000-Val10000.hdf5'
