defaults:
  - _synthetic_env_base
  - _self_
name: robosuite_lift
tags: "robosuite_lift"
datadir: "datasets/RobosuiteLift-Seed0-Tr300000-Val30000.hdf5"
dataset_checkpoint:
    entity: ''
    project: ''
    run_id: ''
    file: 'datasets/RobosuiteLift-Seed0-Tr300000-Val30000.hdf5'
