name: 'SAC'
orig: True
algo_kwargs:
    learning_rate: 3e-4
    train_freq: 1
    gradient_steps: 1
    learning_starts: 1000
    buffer_size: 1000000
    gamma: 0.95
    batch_size: 512
    ent_coef: auto
    tau: 0.01